OPENAI_API_KEY = "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"

YELP_API_KEY = "ZwS_K8NF8XsXJcPh1FuscE8BnoPlKovku9_YTo2qgwdpPiBbw8B0xZgKA8Dk_bdG2ti8TNgtQ8grUX69rm0OpSLF3g-4Gw4ik6HM_IwDIgWfOwMIOGYt9ErygBPzZ3Yx"


